/**
 * Check Environment Configuration
 * Validates that all required .env variables are set
 */

import dotenv from 'dotenv';
import { existsSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const envPath = join(__dirname, '..', '.env');

console.log('🔍 Checking Environment Configuration\n');
console.log('='.repeat(50));

// Check if .env exists
if (!existsSync(envPath)) {
  console.error('❌ .env file is missing!');
  console.error(`   Expected: ${envPath}`);
  console.error('\n💡 Solution: Copy .env.example to .env and update values');
  console.error('   cp .env.example .env');
  process.exit(1);
}

console.log('✅ .env file exists\n');

// Load environment variables
dotenv.config({ path: envPath });

// Required variables (DB_PASS can be empty if MySQL has no password)
const required = {
  'DB_HOST': process.env.DB_HOST,
  'DB_USER': process.env.DB_USER,
  'DB_NAME': process.env.DB_NAME,
  'JWT_SECRET': process.env.JWT_SECRET,
};

// Optional but should exist (can be empty)
const optionalButShouldExist = {
  'DB_PASS': process.env.DB_PASS,
};

const optional = {
  'PORT': process.env.PORT || '5001 (default)',
  'NODE_ENV': process.env.NODE_ENV || 'development (default)',
  'FRONTEND_URL': process.env.FRONTEND_URL || 'http://localhost:5173 (default)',
};

let hasErrors = false;

console.log('📋 Required Variables:');
console.log('-'.repeat(50));
for (const [key, value] of Object.entries(required)) {
  if (!value || value.trim() === '') {
    console.error(`❌ ${key}: NOT SET or EMPTY`);
    hasErrors = true;
  } else {
    const displayValue = key === 'JWT_SECRET' || key === 'DB_PASS' 
      ? `${'*'.repeat(Math.min(value.length, 20))} (hidden)`
      : value;
    console.log(`✅ ${key}: ${displayValue}`);
  }
}

console.log('\n📋 Optional Variables:');
console.log('-'.repeat(50));
for (const [key, value] of Object.entries(optional)) {
  console.log(`✅ ${key}: ${value}`);
}

console.log('\n📋 Database Password:');
console.log('-'.repeat(50));
if (process.env.DB_PASS === undefined) {
  console.error(`❌ DB_PASS: NOT SET (should exist in .env, even if empty)`);
  hasErrors = true;
} else if (process.env.DB_PASS.trim() === '') {
  console.log(`⚠️  DB_PASS: (empty - OK if MySQL root has no password)`);
} else {
  console.log(`✅ DB_PASS: ${'*'.repeat(20)} (hidden)`);
}

if (hasErrors) {
  console.log('\n' + '='.repeat(50));
  console.error('\n❌ Configuration Errors Found!\n');
  console.log('💡 To fix, add these to your .env file:\n');
  
  if (!required.DB_HOST) console.log('DB_HOST=localhost');
  if (!required.DB_USER) console.log('DB_USER=root');
  if (!required.DB_PASS) console.log('DB_PASS=        # Leave empty if no password, or add your MySQL password');
  if (!required.DB_NAME) console.log('DB_NAME=ajh_sports');
  if (!required.JWT_SECRET) {
    console.log('JWT_SECRET=     # Will be auto-generated by: npm run db:fix-admin-login');
  }
  
  console.log('\n⚠️  After updating .env, restart your server: npm restart\n');
  process.exit(1);
} else {
  console.log('\n' + '='.repeat(50));
  console.log('✅ All required environment variables are set!\n');
}

